services:
  db:
    image: postgres:16-alpine
    container_name: notify_db
    environment:
      POSTGRES_USER: notify_user
      POSTGRES_PASSWORD: notify_pass
      POSTGRES_DB: notify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notify_user -d notify_db" ]
      interval: 5s
      timeout: 3s
      retries: 5

  broker:
    image: rabbitmq:3-management-alpine
    container_name: notify_broker
    ports:
      - "5672:5672" # порт для приложения
      - "15672:15672" # веб-морда (логин/пароль: guest/guest)
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    container_name: notify_api
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    command: sh -c "flask --app run db upgrade && gunicorn -b 0.0.0.0:5001 run:app"
  worker:
    build: .
    container_name: notify_worker
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    command: python worker.py
volumes:
  postgres_data:
